# Generated by Django 5.0.6 on 2024-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(db_column='nome', max_length=255, unique=True),
        ),
    ]
