# Generated by Django 3.2.13 on 2024-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=191)),
                ('endereco', models.CharField(max_length=191)),
                ('numero', models.CharField(max_length=191)),
                ('complemento', models.CharField(blank=True, max_length=191, null=True)),
                ('bairro', models.CharField(max_length=191)),
                ('cidade', models.CharField(max_length=191)),
                ('ativo', models.IntegerField()),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
    ]
