# Generated by Django 3.2.13 on 2024-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEmpresarial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=191)),
                ('nome_fantasia', models.CharField(max_length=191)),
                ('cnpj', models.CharField(blank=True, max_length=191, null=True)),
                ('cnes', models.CharField(max_length=8)),
                ('telefone', models.CharField(blank=True, max_length=191, null=True)),
                ('celular', models.CharField(blank=True, max_length=191, null=True)),
                ('email', models.CharField(blank=True, max_length=191, null=True)),
                ('observacoes', models.CharField(max_length=191)),
                ('sigla', models.CharField(max_length=191)),
                ('ativo', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'grupo_empresarial',
                'managed': False,
            },
        ),
    ]
