# Generated by Django 3.2.13 on 2024-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(max_length=191)),
                ('unidade_federativa_id', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'unidade_federativa',
                'managed': False,
            },
        ),
    ]
